export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const FETCH_NEXT_POST_REQUEST = "FETCH_NEXT_POST_REQUEST";
export const FETCH_NEXT_POST_SUCCESS = "FETCH_NEXT_POST_SUCCESS";
export const FETCH_NEXT_POST_FAILURE = "FETCH_NEXT_POST_FAILURE";

export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";
